// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD47hlCjNYyiUQbPryHyJGakMmYG4e_zNU',
    appId: '1:658904300640:web:a647b62713d4d31af4d705',
    messagingSenderId: '658904300640',
    projectId: 'portfolio-f16dd',
    authDomain: 'portfolio-f16dd.firebaseapp.com',
    storageBucket: 'portfolio-f16dd.appspot.com',
    measurementId: 'G-Q26GVEDEQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF7lCUVMGw8j25tW01yz3ZkoSiGpGoJQs',
    appId: '1:658904300640:android:d20c9890685f54b3f4d705',
    messagingSenderId: '658904300640',
    projectId: 'portfolio-f16dd',
    storageBucket: 'portfolio-f16dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYFGnXZlw-fASic0WXfKAIPxhVcjyPi-g',
    appId: '1:658904300640:ios:30d127b4089ff14af4d705',
    messagingSenderId: '658904300640',
    projectId: 'portfolio-f16dd',
    storageBucket: 'portfolio-f16dd.appspot.com',
    iosBundleId: 'com.example.myPortfilio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYFGnXZlw-fASic0WXfKAIPxhVcjyPi-g',
    appId: '1:658904300640:ios:88ec9cbbb004b95bf4d705',
    messagingSenderId: '658904300640',
    projectId: 'portfolio-f16dd',
    storageBucket: 'portfolio-f16dd.appspot.com',
    iosBundleId: 'com.example.myPortfilio.RunnerTests',
  );
}
